import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/footer/Footer";
import "./globals.css";
import { Urbanist } from "next/font/google";

const inter = Urbanist({ subsets: ["latin"] });

export const metadata = {
  title: "TRAFULL LANDING PAGE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
